databases:
  - name: workforceoptix-db
    databaseName: workforceoptix
    user: workforce
    plan: free

services:
  - type: web
    name: workforceoptix
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn run:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: workforceoptix-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
